import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/Style/Tailwind.css"
import "@/Style/Global.css"
import { ToastContainer } from 'react-toastify';
import Whatsapp from "@/components/Whatsapp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping App",
  description: "Generated by Abhishek",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-full flex-col">
        <div className="flex min-h-full flex-col">{children}</div>
        <Whatsapp />
      </body>
    </html>
  );
}
